feat: 시큐리티 적용
Doong-Ji/nestalk-backend-spring pull request #26
Opened 2021-02-18 12:39 UTC by hyojin107

## #1

## 🙄 PR 설명
- 시큐리티 적용

## 💡 추가적인 정보
- 빠른 테스트를 위해 h2로 DB를 설정하였는데, 나중에 MariaDB로 변경할 예정

2021-02-18 14:08 UTC, tladbstjsdl reviewed
Good!

2021-02-19 14:41 UTC, dksalsgus commented
Good

2021-02-21 09:29 UTC, HwanChang requested changes
스프링 파트에서 첫 PR 고생 많으셨습니다.
아무래도 이 부분들이 완성이 되어야 다른 이슈들도 빠른 진행이 될 것 같아서 빨리 리뷰를 드리려했는데 조금 늦었네요.

수정이 필요한 부분 몇 개 체크해뒀으니 확인 부탁드려요~~
수고 많으셨습니다!!
🙌🙌🙌🙌

2021-02-21 09:29 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/config/SecurityConfig.java
> +               .and()
모든 권한을 풀어주는것도 지금은 상관 없지만 되도록 로그인, 회원가입 같은 사용자 인증없이 들어가는 URL 외에는 전부 USER 권한만 접근 가능하도록 설정 해주세요.

그리고 ADMIN, USER 와 같이 문자열을 하드코딩 하는 것 보다는 enum을 사용해서 Role을 관리해주는게 좋을 것 같습니다.

2021-02-21 09:29 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/config/SecurityConfig.java
> +    }
UserDetailsServiceImpl  클래스에 @Service 어노테이션을 달아뒀기 때문에 따로 빈등록이 없어도 될 것 같습니다.

2021-02-21 09:29 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/config/user/UserDetailsServiceImpl.java
> +    public UserDetails loadUserByUsername(String id) throws UsernameNotFoundException {
메소드 명은 loadUserByUsername인데 조회 기준이 id 값이네요.
메소드 명을 수정해줘야 할 것 같습니다.

2021-02-21 09:29 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/config/user/UserDetailsServiceImpl.java
> +                .getResultList();
간단한 조회인데 쿼리를 직접 사용한다면 JPA를 사용하는 의미가 없을 것 같아요.
다른 방식으로 조회를 해보는게 어떨까요?

그리고 어차피 userId는 중복으로 insert가 되지 않기 때문에 조회 결과는 List로 받을 필요가 없습니다.

2021-02-21 09:29 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/config/user/UserDetailsServiceImpl.java
> +        }
위에서 말씀드렸듯 List 타입으로 받지 않는다면 Optional을 활용하여 좀 더 간결한 코드를 작성할 수 있을 것 같아요.

2021-02-21 09:29 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/config/user/UserDetailsServiceImpl.java
> +        String roleName = userEntity.getRole().equalsIgnoreCase("admin") ? "ADMIN" : "USER";
마찬가지로  Optional API를 사용하면 좋을 것 같습니다.

그리고 ADMIN, USER 를 enum으로 관리해주면 좋겠네요.

2021-02-21 09:29 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/vo/UserVo.java
> +public class UserVo {
JPA에서 Entity 개념으로 사용되기 때문에 클래스 명에 VO를 붙이지 않아도 될 것 같아요.

2021-02-21 09:29 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/vo/UserVo.java
> +    public UserVo() {
빈 생성자를  public으로 사용할 필요가 있을까요?

2021-02-21 09:29 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/vo/UserVo.java
> +    }
Entity 에서는 Setter를 사용하지 않는게 좋습니다.
그리고 Getter는 lombok을 사용한다면 Entity 라인수를 줄여줄 수 있을 것 같아요.

2021-02-21 11:31 UTC, syh24 commented on src/main/java/com/doongji/nestalk/config/user/UserDetailsServiceImpl.java
> +                .getResultList();
저도 간단한 쿼리 조회는 Data JPA를 사용하는 것이 좋을 것 같습니다. 또한 쿼리 작성도 repository에서 하면 좋을 것 같아요!!

2021-02-21 14:11 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/config/user/UserDetailsServiceImpl.java
> +                .getResultList();
넵 그게 훨씬 적절한 방식같아요!

2021-02-23 06:36 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/enums/RoleType.java
> +    ADMIN("ROLE_ADMIN"), USER("ROLE_USER");
enum 으로 Role 관리 좋아요!
👍👍👍

2021-02-25 16:03 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/config/user/UserDetailsServiceImpl.java
> +                .getResultList();
넵 처리했습니다!

2021-02-25 16:03 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/config/SecurityConfig.java
> +               .and()
네 수정했습니다

2021-02-25 16:06 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/config/SecurityConfig.java
> +    }
제거했습니다. 감사합니다.

2021-02-25 16:09 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/config/user/UserDetailsServiceImpl.java
> +                .getResultList();
수정했습니다. 감사합니다

2021-02-26 13:42 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/vo/UserVo.java
> +    }
수정했습니다.

2021-02-27 02:18 UTC, tladbstjsdl requested changes
Entity 이름을 단수형으로 하는게 좋아보여요. 나머지는... 제 수준에서는 다 좋아보이네요.

2021-02-27 03:32 UTC, tladbstjsdl approved these changes
수고하셨습니다.

2021-02-27 04:00 UTC, HwanChang approved these changes
고생하셨습니다.
회원가입/로그인 구현 후 JWT 적용하여 새로운 PR 보내주세요!
🙌🙌🙌🙌

2021-02-27 04:55 UTC, syh24 approved these changes

2021-02-27 04:55 UTC, syh24 commented
고생하셨습니다

2021-02-27 05:56 UTC, merged