Feature/#8 find password
Doong-Ji/nestalk-backend-spring pull request #28
Opened 2021-03-04 07:23 UTC by syh24

## #이슈번호
 #8 
## 🙄 PR 설명
-  비밀번호 찾기를 통해 임시 비밀번호를 발급받는다.

## 🌞 변경된 내용
- User Entity 내용 추가
- UserRestController 내용 추가
- EmailService 구현
- 테스트 케이스 추가

## 💡 추가적인 정보
- application.yml 파일에서 자신의 구글 이메일과 비밀번호 작성 (메일 보낼 때 필요) 이때 자신의 구글 계정에서 설정 -> 보안 -> 보안 수준이 낮은 앱 허용 을 해주어야한다.

아직 Eception 처리를 잘 할줄 몰라서 피드백과 리뷰 부탁드립니다.

2021-03-04 11:58 UTC, dksalsgus submitted a review, later dismissed
수고하셨습니다

2021-03-04 15:31 UTC, hyojin107 requested changes
수고하셨습니다. 🙌🙌
테스트코드를 꼼꼼하게 작성해주셔서 좋은 것 같습니다.
수정이 필요한 부분을 몇개 체크해 드렸습니다. 참고부탁드려요!😃😳😳

2021-03-04 15:31 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/email/EmailService.java
> +            Random rnd = new Random();
랜덤값을 직접 생성안하고도 UUID를 이용해서 임시비밀번호를 만들 수 있을 것 같습니다. 
UUID를 생성해서 6~8글자를 추출하면, 해당 로직을 직접 구현하지 않으면서도 확실한 랜덤값을 생성할 수 있으니 효율적일 것 같습니다.

2021-03-04 15:31 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/config/SecurityConfig.java
> +                .antMatchers(HttpMethod.POST,"/api/v?/user/password").permitAll()
해당 url 요청이 유일하기 때문에, 첫번째 인자값인 POST는 생략할 수 있습니다! 참고해주세요 😃

2021-03-04 15:31 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/controller/v1/user/UserRestController.java
> +    private final GeneralExceptionHandler generalExceptionHandler;
GeneralExceptionHandler  객체는 사용되지 않은 것 같은데, 혹시 선언한 이유가 있을까요?

2021-03-04 15:31 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/service/user/UserService.java
> +    }
void로 return값이 아무것도 없으면, DB에 값이 잘 들어갔는지 확인하기 어려울 것 같습니다.
Boolean 타입으로(혹은 다른 타입으로도)  반환해서, 트랜잭션 관리가 잘 이루어졌는지 확인하는 것이 좋을 것 같습니다.

2021-03-05 00:35 UTC, dksalsgus reviewed
딱히 문제 없어보여 승인하였는데 코드 승인시 조금 더 주의하도록 하겠습니다~

2021-03-05 00:40 UTC, HwanChang commented
> 딱히 문제 없어보여 승인하였는데 코드 승인시 조금 더 주의하도록 하겠습니다~

코드리뷰는 문제 지적만 하는게 아니기 때문에 문제가 없다면 잘 된 부분도 리뷰해주면 좋을 것 같아요.
리뷰를 보시는 다른 분들도 이게 잘된 코드구나 하고 참고를 할 수 있으니까요~

문제가 없어보이고 잘 된 부분도 안보인다면 승인 보다는 코멘트를 달아주는게 좋을 것 같아요.
승인이 두명 되면 누구든 merge가 가능하기 때문에 승인은 신중한 판단이 필요해요! 👋👋

🤜🤛

2021-03-05 03:27 UTC, syh24 commented on src/main/java/com/doongji/nestalk/email/EmailService.java
> +            Random rnd = new Random();
UUID로 수정했습니다. 좋은 아이디어 감사합니다!

2021-03-05 03:28 UTC, syh24 commented on src/main/java/com/doongji/nestalk/config/SecurityConfig.java
> +                .antMatchers(HttpMethod.POST,"/api/v?/user/password").permitAll()
나중에 비밀번호 변경 url 때문에 혹시 명시한건데, 일단은 삭제해뒀습니다.

2021-03-05 03:28 UTC, syh24 commented on src/main/java/com/doongji/nestalk/controller/v1/user/UserRestController.java
> +    private final GeneralExceptionHandler generalExceptionHandler;
사용해보려다가 실수로 안지운거 같습니다. 수정했습니다.

2021-03-05 03:29 UTC, syh24 commented on src/main/java/com/doongji/nestalk/service/user/UserService.java
> +    }
Boolean 타입으로 수정했습니다. 좋은 리뷰 감사합니다!!

2021-03-05 17:33 UTC, tladbstjsdl requested changes
Exception 종류에 따라 메세지를 다르게 하는게 좋아보여요. 둘이 발생하는 경우가 다르니까요.

2021-03-05 17:34 UTC, tladbstjsdl approved these changes
제 지식 밖의 범주가 나오기 시작하네요...

2021-03-05 17:35 UTC, tladbstjsdl approved these changes
제 파트도 못해서 쩔쩔매는 와중에 이런건 뭐가 뭔지도 모르겠네요... UUID 사용해서 깔끔해진건 좋네요.

2021-03-05 17:36 UTC, tladbstjsdl approved these changes

2021-03-06 10:15 UTC, KangWookOh commented
배울게...진짜 많네요ㅠㅠ

2021-03-08 12:57 UTC, hyojin107 requested changes
👍👍

2021-03-08 12:57 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/email/EmailService.java
> +        String temp = uuid.toString().substring(0, 8);
```suggestion
       String temp = UUID.randomUUID().toString().substring(0, 8);
```
이렇게 한줄로 줄이면 깔끔할것같아요!

2021-03-08 12:57 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/service/user/UserService.java
> +        return passwordEncoder.matches(password,user.getPassword()) ? true : false;
matches() 메서드 반환값이 boolean이기 때문에, 삼항연산자를 사용할 필요가 없어보입니다..!

2021-03-08 13:09 UTC, jypark92 commented on src/main/java/com/doongji/nestalk/email/EmailService.java
> +        String temp = uuid.toString().substring(0, 8);
효진님이 좋은 부분 이야기해주신 것 같아요. 개인적으로 직감적으로 와닿는다는 생각이 들었습니다. 이렇게 사용할 수 있구나 하나 배워갑니다

2021-03-28 12:54 UTC, hyojin107 commented
필요한 기능들을 정리한 뒤, 추후에 개발을 진행하기 위해 close합니다.

2021-03-28 12:54 UTC, closed without merging