Feature/#7 find email
Doong-Ji/nestalk-backend-spring pull request #29
Opened 2021-03-09 14:20 UTC by syh24

## #7 
## 🙄 PR 설명
- 아이디 찾기 (유저 이름과 휴대폰 번호를 이용해서 유저 이메일을 찾는다.)

## 🌞 변경된 내용
- UserRepository 수정
- UserService 수정
- UserController 로직 추가
- 테스트 케이스 추가

## 💡 추가적인 정보
- 리뷰와 피드백 부탁드립니다!!

2021-03-10 00:01 UTC, dksalsgus reviewed
고생하셨습니다 제 지식선에선 크게 잘못된 부분 없어보이네요 👍

2021-03-10 13:59 UTC, hyojin107 requested changes

2021-03-10 13:59 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/service/user/UserService.java
> +                .orElseThrow(() -> new NoSuchElementException("유저가 존재하지 않습니다."));
유저 객체를 가져오는데 user가 없는 거니까, Exception을 UserNotFoundException()으로 처리하는게 낫지않을까요?🤔

2021-03-11 10:08 UTC, syh24 commented on src/main/java/com/doongji/nestalk/service/user/UserService.java
> +                .orElseThrow(() -> new NoSuchElementException("유저가 존재하지 않습니다."));
수정했습니다.

2021-03-11 13:27 UTC, hyojin107 approved these changes
수고하셨습니다. 제가 보기엔 흠잡을 데 없이 완벽한 것 같아요! 😎
특히 테스트 코드에서 url로 API를 호출해서 테스트 한 부분이 좋은것 같습니다. 👍👍

2021-03-11 13:27 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/controller/v1/user/UserRestController.java
> +import java.util.NoSuchElementException;
import 정리해주시면 좋을 것 같아요! ㅎㅎ

2021-03-12 03:34 UTC, HwanChang requested changes
전체적으로 조금씩 수정이 필요한 부분들 체크해뒀습니다.
그리고 커밋 하기 전 항상 코드 정렬을 신경 써주세요.
수고하셨습니다.
🙌🙌🙌🙌

2021-03-12 03:34 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/user/UserRestController.java
> +    public ResponseEntity<?> checkEmail (@RequestBody FindEmailRequest request){
리턴되는 타입을 정확히 써주면 좋을 것 같아요.

2021-03-12 03:34 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/user/dto/FindEmailRequest.java
> +@Data
lombok의 @Data 는 되도록 사용하지 않는게 좋습니다.

2021-03-12 03:34 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/user/dto/FindEmailRequest.java
> +    @ApiModelProperty (value = "사용자 이름", required = true)
사소한거지만 전체적으로 코드 정리가 필요한 부분이 좀 있는거같아요.

```suggestion
    @ApiModelProperty(value = "사용자 이름", required = true)
```

2021-03-12 03:34 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/user/dto/FindEmailResponse.java
> +@Data
여기도 마찬가지로 lombok 사용 시 주의가 필요합니다.
lombok은 개발 시 편리함을 제공해주지만 제대로 쓰지 않는다면 오히려 독이라고 생각해요.
적절한 위치에 정확하게 쓰지 않는다면 직접 구현하는게 더 나은 것 같습니다.

2021-03-12 03:34 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/user/dto/FindEmailResponse.java
> +    @ApiModelProperty (value = "사용자 이메일", required = true)
```suggestion
    @ApiModelProperty(value = "사용자 이메일", required = true)
```

2021-03-12 03:34 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/service/user/UserService.java
> +    public User findId(String name, String phone) {
메소드 명을 좀 더 명시적으로 작성해주면 좋을 것 같습니다.
findId 라는 이름으로는 메소드의 기능이 좀 추상적으로 느껴져요.

2021-03-12 03:34 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/user/dto/FindEmailRequest.java
> +    public FindEmailRequest (String name, String phone){
```suggestion
    public FindEmailRequest (String name, String phone) {
```

2021-03-12 03:34 UTC, HwanChang commented on src/test/java/com/doongji/nestalk/controller/v1/user/UserRestControllerTest.java
> +
```suggestion
```

2021-03-12 03:34 UTC, HwanChang commented on src/test/java/com/doongji/nestalk/controller/v1/user/UserRestControllerTest.java
> +        return userService.join("abc@gmail.com","test","123456789","010-1234-5678", LocalDate.now());
Controller 테스트 시에 회원가입 로직을 타는게 맞을까요?
UserService의 회원가입 쪽에서 오류가 발생했는데 해당 문제로 Controller 테스트가 실패한다면 적절한 테스트라고 볼 수 있는지 생각해봐야해요.

2021-03-12 03:34 UTC, HwanChang commented on src/test/java/com/doongji/nestalk/service/user/UserServiceTest.java
> +    }
이 부분은 테스트 목적이 명확하지 않은 것 같습니다.
이메일 찾기 테스트라면 적절한 이메일 값만 넘어오도록 확인을 해야하는데 현재는 사용자명, 전화번호로 user를 조회하는 테스트네요.
목적에 맞는 테스트 코드가 작성되면 좋을 것 같습니다.

2021-03-12 04:56 UTC, syh24 commented on src/main/java/com/doongji/nestalk/controller/v1/user/UserRestController.java
> +    public ResponseEntity<?> checkEmail (@RequestBody FindEmailRequest request){
리턴 타입 명시했습니다.

2021-03-12 04:57 UTC, syh24 commented on src/main/java/com/doongji/nestalk/controller/v1/user/dto/FindEmailRequest.java
> +    @ApiModelProperty (value = "사용자 이름", required = true)
인텔리제이 자동정렬 체크가 잘못되어있었던거 같아요. 수정했습니다.

2021-03-12 04:58 UTC, syh24 commented on src/main/java/com/doongji/nestalk/service/user/UserService.java
> +    public User findId(String name, String phone) {
메소드 이름 수정했습니다.

2021-03-12 04:59 UTC, syh24 commented on src/test/java/com/doongji/nestalk/controller/v1/user/UserRestControllerTest.java
> +        return userService.join("abc@gmail.com","test","123456789","010-1234-5678", LocalDate.now());
그 부분에 대해서 미쳐 생각하지 못했던거 같아요. 수정했습니다. 좋은 피드백 감사합니다!!

2021-03-12 05:00 UTC, syh24 commented on src/test/java/com/doongji/nestalk/service/user/UserServiceTest.java
> +    }
UserService 부분에서는 User을 찾아오는거라서 이렇게 짰는데, 실질적으론 이메일만 사용는거 같아 수정했습니다.

2021-03-12 05:06 UTC, syh24 commented on src/main/java/com/doongji/nestalk/controller/v1/user/dto/FindEmailRequest.java
> +@Data
dto 부분에서 @Data를 많이 사용하는거 같아서 저도 지금까지 사용해왔는데, 찾아보니 필요한 어노테이션만 쓰는게 더 좋을 것 같네요. 피드백 감사합니다!

2021-03-12 06:35 UTC, HwanChang commented on src/test/java/com/doongji/nestalk/service/user/UserServiceTest.java
> +    }
이 부분을 간단히 설명드리면 수정하신 UserService의 findUserByNameAndPhone 메소드는 이메일 찾기 로직이 아니라 사용자명, 전화번호로 유저조회 로직입니다.
해당 기능을 통해 이메일을 조회하도록 api를 만드는거구요.

그렇다면 해당 메소드는 이메일 찾기에서만 쓰는게 아니라 다른곳에서도 사용자명과 전화번호를 사용하여 User를 조회할때 사용이 가능한 범용적인 용도이기 때문에 테스트도 이메일 찾는 기능에 대한 테스트가 아니라 사용자명, 전화번호로 User를 조회하는 테스트를 해주는게 맞을 것 같아요.

그게 아니라 해당 메소드에서 이메일 정보만 리턴해준다면 User 조회가 아니라 이메일 찾기에 대한 로직으로 고정되는 거니까 이메일 찾기 테스트를 진행해주는게 맞겠죠?

2021-03-12 06:41 UTC, HwanChang commented on src/test/java/com/doongji/nestalk/controller/v1/user/UserRestControllerTest.java
> +        return userService.join("abc@gmail.com","test","123456789","010-1234-5678", LocalDate.now());
UserRepository를 통해 직접 save 하면 service 로직은 피할 수 있지만 만약 UserRepository에서 문제가 발생한다면 이것도 나중엔 또 테스트에 영향이 가겠죠??
Controller 테스트에 mockito를 사용해보면 지금보다 더 명확한 테스트도 가능할 것 같은데 한 번 고려해보는것도 좋을 것 같아요.
수고했어요!
👍👍

2021-03-13 13:33 UTC, syh24 commented on src/test/java/com/doongji/nestalk/service/user/UserServiceTest.java
> +    }
일단 findUserByNameAndPhone 이 메서드는 이메일 찾기 외에는 사용이 되지 않을 것 같아서 Email을 반환하는 로직으로 수정하였습니다. 그리고 테스트 또한 Email이 제대로 반환되는지만 확인하는 테스트로 수정하였습니다. 앞으로는 테스트는 목적에 맞게 작성하겠습니다!

2021-03-13 13:34 UTC, syh24 commented on src/test/java/com/doongji/nestalk/controller/v1/user/UserRestControllerTest.java
> +        return userService.join("abc@gmail.com","test","123456789","010-1234-5678", LocalDate.now());
일단 mockito를 이용한 테스트로 수정하였는데, 확인하고 피드백 부탁드립니다.

2021-03-13 16:28 UTC, HwanChang commented on src/test/java/com/doongji/nestalk/service/user/UserServiceTest.java
> +    }
이메일을 반환해주는 로직으로 바뀌었으니 findUserByNameAndPhone 라는 네이밍만 로직에 맞춰서 수정해주시면 완벽할 것 같습니다!

2021-03-13 16:30 UTC, HwanChang commented on src/test/java/com/doongji/nestalk/controller/v1/user/UserRestControllerTest.java
> +        return userService.join("abc@gmail.com","test","123456789","010-1234-5678", LocalDate.now());
mockito를 말씀드린지 얼마 안됐는데 금방 적용하신게 대단한 것 같습니다.
앞으로도 테스트에 활용하면 테스트 코드가 더욱 견고해질 것 같아요.
고생하셨습니다!

2021-03-13 16:38 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/service/user/UserService.java
> +        return user.getEmail();
이 부분은 따로 2줄로 나누기보단 Optional의 map을 활용해서 한줄로 깔끔하게 쓸 수 있을 것 같아요.

2021-03-14 02:57 UTC, syh24 commented on src/main/java/com/doongji/nestalk/service/user/UserService.java
> +        return user.getEmail();
수정했습니다.

2021-03-14 02:57 UTC, syh24 commented on src/test/java/com/doongji/nestalk/service/user/UserServiceTest.java
> +    }
수정했습니다.

2021-03-14 03:04 UTC, HwanChang approved these changes
코드가 처음보다 훨씬 깔끔해지고 명확해졌네요.
고생 많으셨습니다.
🙌🙌🙌🙌

2021-03-14 03:09 UTC, HwanChang commented
@syh24 
PR이 열린지 오래됐는데 리뷰 더 해줄 분들은 없는것 같네요.
확인하시는대로 merge 해주시면 될 것 같습니다.
고생하셨어요!!

2021-03-14 04:07 UTC, merged