Feature/#12 add friend
Doong-Ji/nestalk-backend-spring pull request #30
Opened 2021-03-14 15:29 UTC by hyojin107

## #12 

## 🙄 PR 설명
- email을 통해 친구 등록을 한다.

## 🌞 변경된 내용
- Friend 관련 Entity 추가
- User Entity 생성자 추가
- FriendController 추가
- FriendService 추가
- FriendRepository 추가
- 테스트 케이스 추가

## 💡 추가적인 정보
-

2021-03-14 15:47 UTC, HwanChang requested changes
친구등록에 대한 수정이 필요한 부분 몇가지 체크해뒀습니다.
수정이 더 필요한 부분은 이번 리뷰가 수정되면 확인 해보도록 할게요.

커밋 전에 코드 간격 확인 한 번 부탁드려요.
커밋의 단위도 조금 더 잘게 쪼개주면 좋을 것 같습니다.

고생 많으셨습니다.
🙌🙌🙌🙌

2021-03-14 15:47 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/friend/FriendController.java
> +
```suggestion

```

2021-03-14 15:47 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/friend/FriendController.java
> +    @ApiOperation(value = "친구 등록 (JWT 불필요)")
친구 등록에는 JWT가 필요할 것 같아요.

2021-03-14 15:47 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/friend/FriendController.java
> +    @PostMapping(path = "friend/join")
친구등록 url은 /join이 들어갈 필요가 없을 것 같아요.
friend 에 POST로 보내면 될 것 같습니다.

2021-03-14 15:47 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/friend/FriendController.java
> +    public ResponseEntity<FriendDto> join(
메소드 명이 join은 맞지 않는 것 같아요.
친구 등록에 대한 네이밍을 맞춰주면 좋을 것 같습니다.

2021-03-14 15:47 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/friend/FriendController.java
> +            @RequestBody FriendJoinRequest joinRequest
변수명을 객체 이름에 맞춰서 작성해주세요.

2021-03-14 15:47 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/friend/FriendController.java
> +        return ResponseEntity.ok(new FriendDto(friend));
하나의 라인으로 작성이 가능할 것 같아요.

2021-03-14 15:47 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/friend/dto/FriendDto.java
> +    private User friend;
DTO 에서 User 객체를 그대로 반환하면 패스워드가 노출되니 수정이 필요할 것 같습니다.

2021-03-14 15:47 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/friend/dto/FriendDto.java
> +    private User me;
DTO 에서 User 객체를 그대로 반환하면 패스워드가 노출되니 수정이 필요할 것 같습니다.

2021-03-14 15:47 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/entity/user/Friend.java
> +        this.me = new User(userId);
User 객체에 userId만 입력되면 의미가 없는 것 같습니다.
온전한 User가 입력되도록 해주세요.

2021-03-14 15:47 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/entity/user/User.java
> +
필요한 생성자인지 고민해봐야 할 것 같아요.

2021-03-14 15:47 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/repository/friend/FriendRepository.java
> +
```suggestion

```

2021-03-14 15:47 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/service/user/FriendService.java
> +    private final UserRepository userRepository;
```suggestion
    private final UserRepository userRepository;
    
```

2021-03-14 15:47 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/service/user/FriendService.java
> +        return friendRepository.save(new Friend(userId, friend));
map()을 사용하면 코드가 더 간결해질 수 있을 것 같아요.
메소드 명도 수정이 필요할 것 같습니다.

2021-03-14 15:47 UTC, HwanChang commented on src/test/java/com/doongji/nestalk/service/friend/FriendServiceTest.java
> +    }
회원가입을 여기서 다시 테스트를 돌릴 필요는 없습니다.
join을 바로 사용해주면 돼요.

2021-03-14 15:47 UTC, HwanChang commented on src/test/java/com/doongji/nestalk/service/friend/FriendServiceTest.java
> +    void 친구_등록(){
```suggestion
    void 친구_등록() {
```

2021-03-14 15:47 UTC, HwanChang commented on src/test/java/com/doongji/nestalk/service/friend/FriendServiceTest.java
> +        assertThat(friend.getFriend()).isEqualTo(friendEmail);
친구의 이메일로는 회원가입이 되지 않은 것 같은데 테스트가 정상적으로 통과 했나요??

2021-03-14 16:04 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/controller/v1/friend/FriendController.java
> +    @PostMapping(path = "friend/join")
/join 은 사용자 회원가입할 때만 사용하나 보군요. 수정했습니다.

2021-03-14 16:28 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/controller/v1/friend/FriendController.java
> +    public ResponseEntity<FriendDto> join(
수정했습니다. 감사합니다.

2021-03-14 16:33 UTC, hyojin107 commented on src/test/java/com/doongji/nestalk/service/friend/FriendServiceTest.java
> +    }
감사합니다.

2021-03-15 04:23 UTC, syh24 requested changes
전체적으로 잘 작성하셨는데 테스트 코드를 좀 더 탄탄하게 작성하면 좋을 것 같아요. 정말 수고 많으셨습니다!!!

2021-03-15 04:23 UTC, syh24 commented on src/main/java/com/doongji/nestalk/entity/user/Friend.java
> +        this.me = new User(userId);
Entity에서 @Setter는 빼는게 좋을 거 같고, @OneToOne 과  @ManyToOne 은 LAZY 로딩으로 설정해주시면 좋을거 같습니다. @RequiredArgsConstructor도 필요하지 않은거 같습니다.

2021-03-15 04:23 UTC, syh24 commented on src/main/java/com/doongji/nestalk/service/user/FriendService.java
> +    public Friend join(Long userId, String friendEmail){
```suggestion
    public Friend join(Long userId, String friendEmail) {
```

2021-03-15 04:23 UTC, syh24 commented on src/main/java/com/doongji/nestalk/entity/user/Friend.java
> +    public Friend(Long userId, User friend){
```suggestion
    public Friend(Long userId, User friend) {
```

2021-03-15 04:23 UTC, syh24 commented on src/main/java/com/doongji/nestalk/controller/v1/friend/dto/FriendDto.java
> +    public FriendDto(Friend source){
```suggestion
    public FriendDto(Friend source) {
```

2021-03-15 04:23 UTC, syh24 commented on src/test/java/com/doongji/nestalk/service/friend/FriendServiceTest.java
> +    void setup(){
```suggestion
    void setup() {
```

2021-03-15 04:47 UTC, dksalsgus requested changes

2021-03-15 04:47 UTC, dksalsgus commented on src/main/java/com/doongji/nestalk/entity/user/Friend.java
> +        this.me = new User(userId);
추가적으로 기본생성자가 필요할것 같네요 수고하셨습니다 👍

2021-03-16 14:27 UTC, hyojin107 commented
테스트 코드 추가 및 보완하여 다시 올리도록하겠습니다.

2021-03-17 09:05 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/service/user/FriendService.java
> +                        .orElseThrow(() -> new NotFoundException(User.class, friendEmail));
이 부분 검토 한번 해주실 분 계실까요?
email값으로 User객체를 가져오는데, null값이 들어오는 이유를 잘 모르겠네요

2021-03-22 13:42 UTC, syh24 approved these changes
이거 하나만 수정하시면 나머지는 잘하신거 같아요! 수고하셨습니다.

2021-03-22 13:42 UTC, syh24 commented on src/main/java/com/doongji/nestalk/entity/user/User.java
> +    private List<Friend> friends = new ArrayList<>();
OneToMany는 default가 LAZY라서 없어도 될거 같아요

2021-03-22 13:54 UTC, syh24 commented on src/main/java/com/doongji/nestalk/entity/user/User.java
> +    private List<Friend> friends = new ArrayList<>();
User 엔티티에도 ToString이 있는데 여기서도 friends는 exclude해주는게 좋을거 같아요

2021-03-22 14:04 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/entity/user/User.java
> +    private List<Friend> friends = new ArrayList<>();
감사합니다. 수정했습니다

2021-03-22 14:46 UTC, HwanChang requested changes
몇몇 부분만 수정해주면 좋을 것 같습니다.
고생하셨어요!

2021-03-22 14:46 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/friend/FriendController.java
> +        return ResponseEntity.ok(new FriendDto(friend));
이 부분을 한 문장으로 합쳐도 깔끔할 것 같아요

2021-03-22 14:46 UTC, HwanChang commented on src/test/java/com/doongji/nestalk/service/friend/FriendServiceTest.java
> +        userService.join("newdoongji.team@naver.com", "친구친구", "P@ssword1", "010-1111-0000", LocalDate.of(1995, 2, 19));
Friend 관련 테스트에서 회원가입 테스트를 할 필요는 없다고 생각해요.
회원가입 테스트는 UserService에서 테스트를 진행 했기 때문에 여기서는 따로 테스트로 뺄 필요는 없을 것 같습니다.

2021-03-22 14:46 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/entity/friend/Friend.java
> +    public Friend(Long friendId, User me, User friend, String friendNickName) {
객체 필드에 대한 validation 체크를 해주면 좋을 것 같아요

2021-03-22 15:01 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/entity/friend/Friend.java
> +    public Friend(Long friendId, User me, User friend, String friendNickName) {
수정했습니다

2021-03-23 00:25 UTC, hyojin107 commented on src/test/java/com/doongji/nestalk/service/friend/FriendServiceTest.java
> +        userService.join("newdoongji.team@naver.com", "친구친구", "P@ssword1", "010-1111-0000", LocalDate.of(1995, 2, 19));
감사합니다. 수정했습니다.

2021-03-23 00:28 UTC, SGKwon95 commented
제가 아직 초보라서 모르는 어노테이션들이 많네요.. 나중에 참고하겠습니다

2021-03-23 00:56 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/entity/friend/Friend.java
> +    @Column(name = "FRIEND_ID")
DB 네이밍 컨벤션을 따라주면 좋을 것 같습니다.
[MySQL 네이밍 컨벤션 문서](https://dev.mysql.com/doc/internals/en/coding-style.html) 확인 해주세요.

2021-03-23 04:59 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/entity/friend/Friend.java
> +    @Column(name = "FRIEND_ID")
수정했습니다. 감사합니다.

2021-03-23 10:52 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/entity/friend/Friend.java
> +    private User friend;
ERD에서는 user_id, target_id로 설정되어있는데 me, friend로 바꿔서 적용하실건가요??

2021-03-23 11:50 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/entity/friend/Friend.java
> +    private User friend;
까먹었네요.. ㅎㅎㅎ수정했습니다

2021-03-23 11:57 UTC, HwanChang approved these changes

2021-03-23 12:07 UTC, dksalsgus approved these changes
👍

2021-03-23 12:07 UTC, merged