Feature/#7 delete user
Doong-Ji/nestalk-backend-spring pull request #32
Opened 2021-03-17 11:58 UTC by dksalsgus

## #이슈번호
resolve #4 
## 🙄 PR 설명
- 회원탈퇴

## 🌞 변경된 내용
- 회원탈퇴 로직 추가

## 💡 추가적인 정보
- 자바 개발자가 아니라 퇴근 후 시간나는대로 스프링 공부해가며 다른분들 실력만큼 쫓아가도록하겠습니다.
- 못한다고 리뷰로 너무 때리진 말아주세요 👍

2021-03-17 12:51 UTC, hyojin107 requested changes
금방 PR을 올려주셨네요. 수고하셨습니다. 👍
다른분들의 코드도 함께 참고하시면 훨씬 도움이 많이 될 것 같습니다.

2021-03-17 12:51 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/service/user/UserService.java
> +        Optional<User> findUser = userRepository.findById(userId);
회원 탈퇴를 하기 위해서는 pk값만 있으면 되니, 굳이 User객체를 가져올 필요는 없을 것 같습니다.

2021-03-17 12:51 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/service/user/UserService.java
> +        return false;
조건문으로 userId값이 존재하지 않았을 때 로직을 실행시키는 것 보다, orElseThrow()를 이용하여 Exception를 발생시키면 코드가 간결해질 것 같습니다.

2021-03-17 12:51 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/controller/v1/user/UserRestController.java
> +    public ResponseEntity<Boolean> deleteUser(@PathVariable Long userId) {
패쓰변수를 이용하지 않아도 @AuthenticationPrincipal 어노테이션을 사용하여 JwtAuthentication 객체를 가져오면, 로그인 상태의 사용자 정보를 가져올 수 있습니다.

2021-03-18 11:53 UTC, dksalsgus commented on src/main/java/com/doongji/nestalk/controller/v1/user/UserRestController.java
> +    public ResponseEntity<Boolean> deleteUser(@PathVariable Long userId) {
수정했습니다 제가 제대로 이해한건지 확인부탁드려요

2021-03-18 11:53 UTC, dksalsgus commented on src/main/java/com/doongji/nestalk/service/user/UserService.java
> +        return false;
수정했습니다 제가 제대로 이해한건지 확인부탁드려요

2021-03-18 11:54 UTC, dksalsgus commented on src/main/java/com/doongji/nestalk/service/user/UserService.java
> +        Optional<User> findUser = userRepository.findById(userId);
이부분 JPA로 어떻게 userId값만 빼오는지 정확하게 모르겠습니다

2021-03-18 12:06 UTC, hyojin107 requested changes
수고하셨습니다. 🙌

2021-03-18 12:06 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/service/user/UserService.java
> +            userRepository.deleteById(findUser.getUserId());
```suggestion
            userRepository.deleteById(userId);
```
컨트롤러에서 Service에 값을 넘길 때, userId값을 넘기고 있으므로
굳이 findById()로 필요하지 않은 사용자 객체를 불러오지 않아도 될것같다는 말이었습니다.

2021-03-18 13:09 UTC, dksalsgus commented on src/main/java/com/doongji/nestalk/service/user/UserService.java
> +            userRepository.deleteById(findUser.getUserId());
아아 그러네요 새롭게 수정했습니다 놓친부분 알려주셔서 감사합니다

2021-03-19 04:36 UTC, hyojin107 requested changes

2021-03-19 05:08 UTC, dksalsgus commented on src/main/java/com/doongji/nestalk/controller/v1/user/UserRestController.java
> +        return ResponseEntity.ok(userService.deleteById(userId));
select(find)가 아니라 user로 반환은 안되고 delete 쿼리 실행 결과가 0 or 1 로 나올테니 interger로 반환하도록 변경하였습니다.

2021-03-19 05:21 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/controller/v1/user/UserRestController.java
> +        return ResponseEntity.ok(userService.deleteById(userId));
아아 보니까 delete수행할 땐 보통 void로 하는군요. 
생각해보니 회원 삭제하고나면 로그인페이지나 홈으로 갈텐데, 반환값을 줄 필요가없는게 당연하네요. 그대로 가셔도 괜찮을 것 같아요!!

2021-03-19 05:27 UTC, dksalsgus commented on src/main/java/com/doongji/nestalk/controller/v1/user/UserRestController.java
> +        return ResponseEntity.ok(userService.deleteById(userId));
티키타카 해주시니 저도 한번더 찾아보게되고 모르는 부분도 찾아보게되서 도움 많이 되는것 같습니다 감사합니다 👍

2021-03-23 01:06 UTC, hyojin107 requested changes
실행 결과값을 Integer로 받는것은 좋지 않아보여서, 다시 수정요청드렸어요ㅎㅎㅎ
수고많으셨어요😃😃

2021-03-23 01:44 UTC, dksalsgus commented on src/main/java/com/doongji/nestalk/repository/user/UserRepository.java
> +    Optional<Integer> deleteByUserId(Long userId);
리턴타입 없이 그냥 함수로 사용하게되면 컨트롤러에서 리턴값이 없을것 같은데 그래도 괜찮을까요 ??

2021-03-23 01:55 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/repository/user/UserRepository.java
> +    Optional<Integer> deleteByUserId(Long userId);
200 ok 가 아니라 204 no content로 내려주면 될 것 같아요

2021-03-23 02:10 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/repository/user/UserRepository.java
> +    Optional<Integer> deleteByUserId(Long userId);
네네 컨트롤러 리턴값은 상태값만 내보내는 것이 맞는것 같아요. 
Integer를 내보내려는 의도가 delete 성공 여부일텐데, 상태값만 봐도 성공여부를 판단할 수 있으니까요🙂

2021-03-23 02:11 UTC, dksalsgus commented on src/main/java/com/doongji/nestalk/repository/user/UserRepository.java
> +    Optional<Integer> deleteByUserId(Long userId);
감사합니다 수정했습니다~

2021-03-23 02:23 UTC, hyojin107 approved these changes
수고많으셨습니다!!👏👏👏

2021-03-23 02:23 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/controller/v1/user/UserRestController.java
> +        userService.deleteById(userId);
```suggestion
        userService.deleteById(jwtAuthentication.userId);
```

2021-03-23 08:25 UTC, HwanChang requested changes
수정이 필요해보이는 부분 체크해뒀습니다.
고생 많으셨어요~
🙌🙌🙌🙌

2021-03-23 08:25 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/user/UserRestController.java
> +    @DeleteMapping(path = "user/delete")
```suggestion
    @DeleteMapping(path = "user")
```

DELETE Method를 썼다면 굳이 url에 delete를 또 추가할 필요는 없을 것 같아요.

2021-03-23 08:25 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/user/UserRestController.java
> +    public ResponseEntity<?> deleteUser(@AuthenticationPrincipal JwtAuthentication jwtAuthentication) {
ResponseEntity에 정확한 타입을 명시해주는게 좋을 것 같습니다.

2021-03-23 08:39 UTC, dksalsgus commented on src/main/java/com/doongji/nestalk/controller/v1/user/UserRestController.java
> +    public ResponseEntity<?> deleteUser(@AuthenticationPrincipal JwtAuthentication jwtAuthentication) {
모두 수정했습니다 다만 void 인 경우 ResponseEntity가 어떤타입으로 바인딩 되어야하는지 모르겠어서 Void 객체로 해두었는데 맞나요 ? 찾아보니 Void 혹은 그냥 ResponseEntity 를 사용하는것 같던데

2021-03-29 08:52 UTC, syh24 approved these changes
수고하셨습니다. 제가 보기엔 괜찮은거 같습니다.

2021-03-30 00:27 UTC, HwanChang approved these changes

2021-04-05 05:16 UTC, merged