Feature/#16 create profile
Doong-Ji/nestalk-backend-spring pull request #33
Opened 2021-03-17 15:45 UTC by qlalzl9

## #16 

## 🙄 PR 설명
- 프로필 등록 기능 구현

## 🌞 변경된 내용
- Profile 엔티티 추가
- ProfileController 추가
- ProfileService 추가
- ProfileRepository 추가
- 프로필 등록 테스트 추가

## 💡 추가적인 정보
- 현재 테스트에서 이미지 관련 테스트를 문자열로 진행했는데 더 나은 테스트 방법이 있으면 의견 부탁드리겠습니다.

2021-03-18 07:27 UTC, hyojin107 requested changes
첨부파일을 요청받아서 서버에 저장하는 로직이 없는것같습니다.

2021-03-18 07:27 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/controller/v1/profile/dto/ProfileRequest.java
> +    private String backgroundImage;
request로 들어오는 것은 파일 경로가 아닌 이미지파일이기 때문에
첨부파일을 받을 때는 String 타입이 아니라 MultipartFile로 받아야합니다.

2021-03-19 06:41 UTC, HwanChang requested changes
JPA와 JAVA API 활용을 조금만 더 신경 써주면 좋을 것 같습니다.
고생하셨어요.
커밋 전에 코드 포맷을 확인 꼭 하고 커밋해주세요.
커밋도 조금 더 세분화 해주면 좋을 것 같습니다.
👐👐👐

2021-03-19 06:41 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/profile/ProfileRestController.java
> +    @PostMapping(path = "profile/create")
```suggestion
    @PostMapping(path = "profile")
```

POST 메소드를 사용하기 때문에 create라는 url 경로를 쓰지 않아도 될 것 같습니다.

2021-03-19 06:41 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/controller/v1/profile/dto/ProfileDto.java
> +}
```suggestion
    }
    
}

```

2021-03-19 06:41 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/entity/profile/Profile.java
> +    }
```suggestion
    }
    
```

2021-03-19 06:41 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/repository/profile/ProfileRepository.java
> +}
```suggestion
}

```

2021-03-19 06:41 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/service/profile/ProfileService.java
> +}
```suggestion
    }
    
}

```

2021-03-19 06:41 UTC, HwanChang commented on src/test/java/com/doongji/nestalk/service/profile/ProfileServiceTest.java
> +    }
ProfileService 테스트를 하는데 회원가입 테스트를 하는 이유가 있을까요?

2021-03-19 06:41 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/entity/user/User.java
> +    }
JPA를 사용하는데 필요한 부분인지 확인이 필요합니다.

2021-03-19 06:41 UTC, HwanChang commented on src/main/java/com/doongji/nestalk/service/profile/ProfileService.java
> +        currentUser.updateProfile(profile);
User와 Profile이 잘 매핑돼있다면 필요한 부분일까요?

2021-03-21 16:17 UTC, HwanChang commented
개발 담당자 변경으로 해당 PR은 close 하겠습니다.

2021-03-21 16:17 UTC, closed without merging