feat: 친구 목록 조회 기능 구현(Test 완료)
Doong-Ji/nestalk-backend-spring pull request #48
Opened 2021-03-31 11:56 UTC by KangWookOh

## #이슈번호

## 🙄 PR 설명
- 어떤 목적을 위한 PR인지 설명

## 🌞 변경된 내용
- 어떤 부분이 수정되었는지 설명

## 💡 추가적인 정보
- PR 관련, 수정된 기능 관련하여 추가로 알아야 할 정보 작성

2021-03-31 16:18 UTC, hyojin107 requested changes
이슈에 맞게 친구 목록을 조회하는 기능을 구현해주시고,
테스트코드를 작성해주세요. 😅

2021-03-31 16:18 UTC, hyojin107 commented on src/test/java/com/doongji/nestalk/service/friend/FriendServiceTest.java
> +        log.info("FriendList: {}", friend);
테스크 케이스가 하나도 없네요..
테스트 코드를 작성해주세요

2021-03-31 16:18 UTC, hyojin107 commented on src/main/java/com/doongji/nestalk/service/friend/FriendService.java
> +    }
친구 목록을 조회하는 기능인데, 왜 Service가 User객체만 조회하고 끝나는건가요..?🙄
친구 목록을 조회하는 기능을 구현해주세요..ㅎㅎ

2021-04-01 00:36 UTC, hyunyfully commented on src/main/java/com/doongji/nestalk/service/friend/FriendService.java
> +    }
목록이면 list로 받아야하지 않을까요?

2021-04-06 07:45 UTC, hyojin107 commented
이슈 담당자 변경으로 인해, 해당 PR을 close합니다.

2021-04-06 07:45 UTC, closed without merging